name: Testing
on:
  push:
    branches: main
    paths-ignore:
      - '.github/workflows/clang-formatter.yml'
      - 'project/discord-rpc/.clang-format'
      - 'LICENSE'
      - 'README.md'
      - 'haxelib.json'
      - 'hxformat.json'
  workflow_dispatch:
jobs:
  Job:
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, macos, ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install Dependencies
        run: |
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git --quiet
          cd "$(haxelib libpath hxcpp)/tools/hxcpp"
          haxe compile.hxml
          cd ${{ github.workspace }}
          haxelib dev hxdiscord_rpc .

      - name: Build Unix
        if: matrix.os == 'macos' || matrix.os == 'ubuntu'
        run: cd sample && haxe build-unix.hxml

      - name: Build Windows
        if: matrix.os == 'windows'
        run: cd sample && haxe build-win.hxml
